version: '3.8'

services:
    # PHP container (with Laravel)
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_php
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network

    # Nginx container
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - laravel_network

    # MySQL container
    db:
        image: mysql:8.0
        container_name: laravel_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todolaravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root_password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    # Composer container (optional but useful for managing dependencies)
    composer:
        image: composer:latest
        container_name: laravel_composer
        volumes:
            - .:/var/www
        networks:
            - laravel_network

volumes:
    db_data:
        driver: local

networks:
    laravel_network:
        driver: bridge
